# fly.toml file generated for dbofmmbt on 2023-01-08T23:40:35-03:00

app = "dbofmmbt"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  http_checks = []
  internal_port = 7070
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    port = 7070

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "5s"
    timeout = "1s"
